"""cascade(patient)/set null(user) FK 정책 적용

Revision ID: 92c71c6e6a20
Revises: 62fdbffda729
Create Date: 2026-06-09 17:45:11.907631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '92c71c6e6a20'
down_revision: Union[str, Sequence[str], None] = '62fdbffda729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ai_analysis_results_ibfk_1'), 'ai_analysis_results', type_='foreignkey')
    op.create_foreign_key(None, 'ai_analysis_results', 'medical_records', ['record_id'], ['id'], ondelete='CASCADE')
    op.alter_column('medical_records', 'user_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.drop_constraint(op.f('medical_records_ibfk_2'), 'medical_records', type_='foreignkey')
    op.drop_constraint(op.f('medical_records_ibfk_1'), 'medical_records', type_='foreignkey')
    op.create_foreign_key(None, 'medical_records', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'medical_records', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.alter_column('xray_images', 'uploader_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.drop_constraint(op.f('xray_images_ibfk_2'), 'xray_images', type_='foreignkey')
    op.drop_constraint(op.f('xray_images_ibfk_1'), 'xray_images', type_='foreignkey')
    op.create_foreign_key(None, 'xray_images', 'medical_records', ['record_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'xray_images', 'users', ['uploader_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'xray_images', type_='foreignkey')
    op.drop_constraint(None, 'xray_images', type_='foreignkey')
    op.create_foreign_key(op.f('xray_images_ibfk_1'), 'xray_images', 'medical_records', ['record_id'], ['id'])
    op.create_foreign_key(op.f('xray_images_ibfk_2'), 'xray_images', 'users', ['uploader_id'], ['id'])
    op.alter_column('xray_images', 'uploader_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.create_foreign_key(op.f('medical_records_ibfk_1'), 'medical_records', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key(op.f('medical_records_ibfk_2'), 'medical_records', 'users', ['user_id'], ['id'])
    op.alter_column('medical_records', 'user_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'ai_analysis_results', type_='foreignkey')
    op.create_foreign_key(op.f('ai_analysis_results_ibfk_1'), 'ai_analysis_results', 'medical_records', ['record_id'], ['id'])
    # ### end Alembic commands ###
